name: jasonw
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  html: ^0.14.0+2
  scoped_model: ^0.3.0
  http: ^0.12.0+1
  toast: ^0.1.5
  shared_preferences: "^0.5.1+2"
  zendesk: ^1.0.1
  datetime_picker_formfield: ^0.1.8
  custom_chewie: ^0.7.0
  flutter_calendar_carousel: ^1.3.18
  table_calendar: ^2.0.1
  calendar_view_widget: ^0.1.6
  flutter_calendar: ^0.0.1
  flutter_clean_calendar: ^1.0.1
  charts_flutter: ^0.8.0
  calendarro: ^1.0.0
  flutter_circular_chart: ^0.1.0
  path_drawing: ^0.4.0
  keyboard_avoider: ^0.1.2
  dash_chat: ^1.0.6
  country_pickers: ^1.1.0
  firebase_messaging: ^5.1.6
  in_app_purchase: ^0.2.2+2
  bubble: ^1.1.9+1
  audioplayers: any
  cached_network_image: any
  webview_flutter: ^0.3.19+7
  flutter_datetime_picker: ^1.3.5
  # flutter_local_notifications: ^0.6.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/Splash.png
    - images/login-img.png
    - images/about-us.png
    - images/chat.png
    - images/daily-plan.png
    - images/inspiration.png
    - images/journal.png
    - images/reflect.png
    - images/see-me.png
    - images/happening.png
    - images/JASON-LOGO-FINAL-4.png
    - images/dots.png
    - images/heal.png
    - images/product_icon.png
  fonts:
     - family: opensans
       fonts:
         - asset: fonts/OpenSans-Regular.ttf
         - asset: fonts/OpenSans-Semibold.ttf
           weight: 600
     - family: anenir
       fonts:
         - asset: fonts/Avenir-Roman.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
